format = """
[▒▓](#a3aed2)\
[ $username@$hostname ](bg:#a3aed2 fg:#999999)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[username]
style_user = 'bg:#a3aed2 fg:#666677'
style_root = 'bg:#a3aed2 fg:#cc0000'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
style = "bg:#a3aed2 fg:#666677"
format = "[$hostname]($style)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'


[time]
disabled = false
time_format = "%a %T" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)'
